# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            master DTCT
tagline:          'Master Design Transdisciplinaire, Cultures & Territoires'
description:      'Le site du Master Design Transdisciplinaire, Cultures et Territoires (UT2J, Toulouse, France).'
url:              http://master-dtct.github.io/
baseurl:          ""

author:
  name:           'Ã‰quipe du Master DTCT'

# Gems
plugins: [jekyll-paginate, jekyll-gist]
paginate: 5
paginate_path: "page:num"


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/master-dtct
