# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Master DTCT
tagline:          'A Jekyll theme'
description:      'Le site du Master Design Transdisciplinaire : Culture et Territoires. Suivez-nous sur <a href="https://twitter.com/" target="_blank">@masterDTCT</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Ã‰quipe du Master DTCT'
  url:            https://twitter.com/mdo

# Gems
gems: [jekyll-paginate, jekyll-gist]
paginate: 5
paginate_path: "page:num"



# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde




